### ISSUE TITLE
speed on Jetson Nano

### ISSUE THREAD

**Issue by zhangchenwei115** [mathblue/Custom-Pose-Estimation-Yaw-Roll-Pitch-detection-tensorrt-compilation#3]
Hi Mathblue, thanks a lot for your great job to convert this model into TensorRT!! it's really helpful to me :)
I have tried the original model without TensoRT on my jetson nano and the FPS is about 2.2PFS. I used the method you said and convert the model into TensorRT and run it on my Nano. It's only got 2 times faster which is about 5.5PFS. is it normal? or I still need to do something to improve the FPS. I hope finally I can get about 15FPS on the pose estimation. Can you give me some advice to improve the speed?

**Comment by mathblue** [comment]
Hi! I'm sorry for the delay, I've been busy with the university...
Anyway I don't remember getting much more than you (around 3 times faster I think) but I didn't even try to find a way to improve it since it was enough for our purposes. I'm sure there are other ways to get it work faster, maybe a completely different architecture, you can gain speed if you don't really care too much about the precision but unfortunately I'm not able to help you, try to explore!
I developed this project in a start-up where I had the Nano and a powerful GPU pc, now I don't even have the Nano at hand for trying...

**Comment by zhangchenwei115** [comment]
Hey, thanks so much for your reply. Now I can confirm that torch2trt works normal since you said that you also get only 3 times faster. I think on my nano it’s also about 3 times faster. Now I am thinking about the pre and post processing of the image may be the problem to slow the FPS . I will try. 
again thanks a lot for your work!
